### ISSUE TITLE
A few questions about this modded bios

### ISSUE THREAD

**Issue by yonnondio** [tarkh/hackintosh#2]
Hi, I found your github channel looking for info about modified bios for Huananzhi F8D and hackintosh optimizations. I would like to know if this bios that seems to be optimized for Xeones 2678 v3 Haswell-EP would work also with Xeones 26xx v4 Boradwell-EP or I would have problems with it.

Thanks again and apologies for the inconvenience.

**Comment by tarkh** [comment]
Hi! Bios turbo hack for unlocking turbo boost on all cores works ONLY for V3 Xeon family. It's impossible to implement same hack on V4. So you can't use `f8dKSM.bin` bios with microcode patch.

But you can use `f8dKS.bin` bios, which does not contains microcode patch, only proper bios presets for Hackintosh on Huananzhi F8D motherboard.

**Comment by yonnondio** [comment]
I know this. I was wondering if I could have problems if I used the Broadwells with this bios. I have finally installed a couple of 2678 v3 to keep the same configuration as best as possible. All OK with Monterey. 
But I can´t update to Ventura. PC resets continuosly during installation. Maybe any EFI option?

Thanks for your labor and help.

**Comment by tarkh** [comment]
Well, there is support of Xeon V4 in F8D specification. So probably it will work with `f8dKS.bin` bios, because there is no difference in CPU support code from original F8D bios.

About macOS versions - my current studio setup is on Monterey and I haven't tried yet Ventura. But I do have feedback from community, that there is a problem to boot Ventura right now. Apple dropped a lot of hardware support on their latest OS, so maybe we have to deal with OpenCore Legacy Patcher. More info: https://dortania.github.io/OpenCore-Legacy-Patcher/VENTURA-DROP.html#current-status
